# Generated by Django 6.0.5 on 2026-05-18 12:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_questions',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('right_answer', models.CharField(max_length=255)),
                ('incorrect_answers', models.TextField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Банк вопросов',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тип тестирования',
                'verbose_name_plural': 'Типы тестирования',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin_role', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_test', models.CharField(choices=[('exam', 'Экзамен'), ('training', 'Тренировка'), ('final', 'Итоговый')], max_length=20)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='SiteWrongTurn.bank_questions')),
                ('types_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='SiteWrongTurn.types')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='SiteWrongTurn.users')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирования',
            },
        ),
        migrations.CreateModel(
            name='Results_testings',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('count_correct', models.IntegerField(default=0)),
                ('count_incorrect', models.IntegerField(default=0)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='SiteWrongTurn.testing')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
            },
        ),
        migrations.AddField(
            model_name='bank_questions',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='SiteWrongTurn.users'),
        ),
    ]
